adding colours to dialog

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -4,9 +4,6 @@ error() { \
     clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
 }
 
-errormsg() { \
-    dialog --colors --title "\Z7\ZbError!" --msgbox "\Z4Invalid Value" 16 60
-    }
 
 welcome() { \
     dialog --colors --title "\Z7\ZbConfigure your Desktop!" --msgbox "\Z4This is a script that will install everythinging I personally use on a daily basis, This script will run using your Normal User account but sometimes it will need root privleges so then its gonna prompt you for a password to make sure to be near your computer. Me personally tho deactivate sudo password prompts but that comes with a security risk hehe. And also if you run this script when you are installing arch linux then it will install everything you need to get started with a base install. But you will need to run this script again when you have installed the base installation of arch \\n\\n-Karl" 16 60
@@ -21,13 +18,17 @@ command_exist() {
 }
 
 
-deactivate_root() { \
+function case_text() {
 
-         # This will deactivate logins for root
-         echo "#####################################################################"
-         echo "##  Deactivating root account for security reasons , if its needed ##"
-         echo "#####################################################################"
-         check_root_if_activated=$(grep "root" /etc/passwd | awk -F : '{print $NF}' | awk -F / '{print $NF}')
-         [ "$check_root_if_activated" != "nologin" ] && usermod_root=$(sudo usermod -s /usr/sbin/nologin root | awk '{print $3}')
+      echo "######################################################################"
+      echo "${RED}Invalid option: -$OPTARG." 1>&2
+      tput reset
+      echo "-f for a full install"
+      echo "-c for only my config files and a few of my terminal applications"
+      echo "-w (hyprland, qtile, xmonad)"
+      echo "-s (zsh, bash, fish)"
+      echo "-d for just my dotfiles,zsh,tmux and starship prompt"
+      echo "-n for no config files (so you wont overwrite your current configs"
+      echo "######################################################################"
 
 }
