fixing spacing

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -1,40 +1,45 @@
 #!/bin/bash
 
+# Error to display a message and leave the script
 error() { \
     clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
 }
 
 
+# Welcome dialog
 welcome_text="This script will install basics programs plus config files 
 that I use on a daily basic so you can quickly be up and running with a new system
 it depends on your choices what you will install. But you can choose shell, window manager etc.
 You can also choose to only get my config files which is useful if you run this on a server"
 
 
+# Welcome dialog
 welcome() { \
-    dialog --colors --title "\Z7\ZbConfigure your Desktop!" --msgbox "\Z4$welcome_text\\n\\n-Karl" 16 60
-    }
+         dialog --colors --title "\Z7\ZbConfigure your Desktop!" --msgbox "\Z4$welcome_text\\n\\n-Karl" 16 60
+}
 
+# gives you a last chance to leave
 Lastchance() { \
-        dialog --colors --title "\Z7\ZbPoint of no Return" --yes-label "Yes Continue with the install" --no-label "No" --yesno "\Z4Up to this point No changes Have been Made. But now the installation will begin if you click yes there will be no going back. Are you sure you want to do this?" 8 60 || error "user choose to exist"
-    }
+         dialog --colors --title "\Z7\ZbPoint of no Return" --yes-label "Yes Continue with the install" --no-label "No" --yesno "\Z4Up to this point No changes Have been Made. But now the installation will begin if you click yes there will be no going back. Are you sure you want to do this?" 8 60 || error "user choose to exist"
+}
 
+# checks if a command exist or not
 command_exist() {
         type "$1" &> /dev/null;
 }
 
-
+# error text that displays when you write a switch incorrectly
 function case_text() {
 
-      echo "${RED}######################################################################"
-      echo "Invalid option: -$OPTARG." 1>&2
-      echo "-f for a full install"
-      echo "-c for only my config files and a few of my terminal applications"
-      echo "-w (hyprland, qtile, awesome)"
-      echo "-s (zsh, bash, fish)"
-      echo "-d for just my dotfiles,zsh,tmux and starship prompt"
-      echo "-n for no config files (so you wont overwrite your current configs"
-      echo "######################################################################"
+        echo "${RED}######################################################################"
+        echo "Invalid option: -$OPTARG." 1>&2
+        echo "-f for a full install"
+        echo "-c for only my config files and a few of my terminal applications"
+        echo "-w (hyprland, qtile, awesome)"
+        echo "-s (zsh, bash, fish)"
+        echo "-d for just my dotfiles,zsh,tmux and starship prompt"
+        echo "-n for no config files (so you wont overwrite your current configs"
+        echo "######################################################################"
 
 }
 
