cleaning up

diff --git a/main b/main
--- a/main
+++ b/main
@@ -6,9 +6,15 @@
 #|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
 #                                     
 # -*- coding: utf-8 -*-
-# Can directly make a choice -c for basic install
-# and -f for full install
+# First I create some switches you can use
+# when you run the script to avoid being asked
+# but no worries if you just run the script
+# it will ask you for input. Like you can choose
+# window manager shell etc. And yes I wond addftinfo
+# the option to install a Desktop Environment using this script
 
+# -c for basic install (Basically just terminal applications and my config files)
+# -f for full install (Here you get to choose an Window Manager too and gets some other things)
 # -w for window manager
 # -s for shell
 # -c for basic install
@@ -22,10 +28,12 @@ while getopts ":w:s:cf" opt; do
      INSTALL_TYPE=full
      ;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      echo "Invalid option: -$OPTARG. Please select hyperland, qtile, or xmonad" 1>&2
+      echo "-w (hyprland, qtile, xmonad)"
+      echo "-s (zsh, bash, fish)"
       exit 1
       ;;
-    w )
+    w)
       case ${OPTARG} in
         "hyprland" )
          WINDOW_MANAGER="$OPTARG"
@@ -33,13 +41,13 @@ while getopts ":w:s:cf" opt; do
         "qtile" )
          WINDOW_MANAGER="$OPTARG"
           ;;
-        * )
+        *)
           echo "Invalid value. Please select hyperland, qtile, or xmonad."
           exit 1
           ;;
       esac
       ;;
-    s )
+    s)
       case ${OPTARG} in
         "zsh" )
          SHELL_CHOICE="$OPTARG"
@@ -50,19 +58,19 @@ while getopts ":w:s:cf" opt; do
         "fish" )
         SHELL_CHOICE="$OPTARG"
           ;;
-        * )
+        *)
           echo "Invalid value. Please select zsh, bash, or fish."
           exit 1
           ;;
       esac
       ;;
-    \? )
+    \?)
          echo "Invalid option: -$OPTARG. Please select hyperland, qtile, or xmonad" 1>&2
          echo "-w (hyprland, qtile, xmonad)"
          echo "-s (zsh, bash, fish)"
          exit 1
       ;;
-    : )
+    :)
          echo "Invalid option: -$OPTARG requires an argument." 1>&2
          echo "-w (hyprland, qtile, xmonad)"
          echo "-s (zsh, bash, fish)"
@@ -74,10 +82,16 @@ done
 
 
 exit
+
 # Gets the hostname of the machine
+# cause why not lol. It is not used right now
+# in this script but I was planing to add a function later on
+# But I have been kinda lazy.
 hostname=$(cat /etc/hostname &> /dev/null)
 
 # Source Variables and all functions
+# So we can get all my functions
+# I wrote them in seperate files to try and stay organized
 for source in $(ls functions | xargs -n1) ; do
       source functions/$source
 done
@@ -87,7 +101,8 @@ for source in $(ls variables | xargs -n1) ; do
 done
 
 
-# Install fzf and dialog if its needed
+# Install fzf and dialog if its needed cause it will be used in the script
+# So we need to install them
 echo "#####################################################"
 echo "## Installing 'dialog' and 'fzf' if not installed ##"
 echo "#####################################################"
@@ -105,6 +120,7 @@ welcome ; clear
 # Didn't use -c or -f
 [ -z "$INSTALL_TYPE" ] && do_settings ; clear
 
+# Asks you one last time if you really wanna continue
 Lastchance ; clear
 
 # If you didn't choocse window manager and choose full install
@@ -115,9 +131,19 @@ if [ "$INSTALL_TYPE" = "full" ] ; then
 
 fi
 
+
+
+# If you didnt choose shell then it will ask you
+[ -z "$SHELL_CHOICE" ] && do_shell
+
+
+# asks you which default browser you want
 [ "$INSTALL_TYPE" = "full" ] && do_browser
 
-    
+
+# Just making some home folders cause why notepad
+# Making Documents,Downloads,Pictures and Videos
+# If they dont already exist
 echo "################################"
 echo "## Making common user folders ##"
 echo "################################" 
@@ -126,6 +152,8 @@ home_folders || error "Failed to create home folders"
 
 clear
 
+# Installs oh-my-tmux which is a plugin manager for tmux
+# Which I really enjoy to use
 echo "############################"
 echo "## Installing oh my tmux ##"
 echo "###########################"
@@ -134,6 +162,11 @@ install_oh_my_tmux || error "failed to install oh my tmux"
 
 clear
 
+
+
+# Installs pfetch from source cloning the repo
+# and runs make install. You can find the function under
+# function directory called install
 echo "###################################"
 echo "## installing pfetch from source ##"
 echo "###################################"
@@ -141,41 +174,48 @@ command_exist pacman && sudo pacman -S --needed --noconfirm base-devel
 
 install_pfetch 
 
+clear
+
+echo "#####################"
+echo "## installing paru ##"
+echo "#####################"
+install_paru
+
+
+
 if [ "$INSTALL_TYPE" = "basic" ] ; then
 
    command_exist pacman && install_pacman_base
 
-        clear
+   clear
    
 fi
 
 
-echo "#########################################################"
-echo "## Getting all my config files and moving them to home ##"
-echo "#########################################################"
-
+# Runs the dotfiles script which clones my dotfiles repo
+# and moves all my configuration files to home
 cd ./scripts
 
-# Runs the dotfiles script
 ./dotfiles.sh 
 
 cd ..
 
 clear
 
-# If you didnt choose shell then it will ask you
-[ -z "$SHELL_CHOICE" ] && do_shell
+# Change default shell
+sudo usermod -s "/bin/$SHELL_CHOICE"
 
-clear
 
 # If you did choose basic install then the script will exit herre
 [ "$INSTALL_TYPE" = "basic" ] && exit
 
 
-# Installs packages 
+# Installs packages for full installation
 if command_exist pacman; then      
 
     install_pacman_full
+
+    pacman -S --needed --noconfirm $WINDOW_MANAGER
 
     clear
 
@@ -183,36 +223,64 @@ fi
 
 clear
 
+
+# If you choose qtile then it will go and do things thats specific for
+# qtile and xorg this is important because hyprland is based on wayland
+# so the dependencies will be diffrent
 if [ $WINDOW_MANAGER = "qtile" ] ; then
 
-if command_exist qtile ; then
+   # Only installs qtile if needed
+   if command_exist qtile ; then
 
-      echo "Qtile is already installed"
+         echo "Qtile is already installed"
 
-else
+   else
 
-      echo "######################"
-      echo "## installing qtile ##"
-      echo "######################"
+         echo "######################"
+         echo "## installing qtile ##"
+         echo "######################"
+         paru -S --needed --noconfirm qtile qtile-extras
 
-      install_qtile || error "failed to install qtile" ; clear
+   fi
 
-fi
+   clear
 
-clear
+   # If slock is installed it wont install it
+   if command_exit slock ; then
 
-if command_exit slock ; then
+         echo "Slock is already installed"
 
-      echo "Slock is already installed"
+   else
+         echo "##################################"
+         echo "## installing slock from source ##"
+         echo "##################################"
 
-else
-      echo "##################################"
-      echo "## installing slock from source ##"
-      echo "##################################"
+         install_slock || error "failed to install slock" ; clear
 
-      install_slock || error "failed to install slock" ; clear
+   fi
 
-fi
+elif [ $WINDOW_MANAGER = "hyprland" ] ; then
+
+
+    paru -S --needed --noconfirm waybar-hyprland-git hyprland-bin swaylock swaybg grim wofi awesome-terminal-fonts adobe-source-code-pro-fonts ttf-jetbrains-mono
+
+
+   # Only installs qtile if needed
+   if command_exist Hyprland ; then
+
+         echo "Hyprland is already installed"
+
+   else
+
+         echo "#########################"
+         echo "## installing hyprland ##"
+         echo "#########################"
+
+         install_hyprland || error "failed to install hyprland" ; clear
+
+   fi
+
+   clear
 
 
 fi
