updating rsync script

diff --git a/scripts/rsync-my-configs b/scripts/rsync-my-configs
--- a/scripts/rsync-my-configs
+++ b/scripts/rsync-my-configs
@@ -1,7 +1,17 @@
 #!/bin/bash
-
+##____  _                      _      
+#|  _ \| |__   ___   ___ _ __ (_)_  __
+#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
+#|  __/| | | | (_) |  __/ | | | |>  < 
+#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
+#                                     
+# -*- coding: utf-8 -*-
 # Script to quickly configure a new system with my configs
+
+
+# Configure variables that I use in this script
 DOTFILES_REPO_PATH="$HOME/dotfiles"
+DMSCRIPTS_REPO_PATH="$HOME/dmscripts"
 
 # imports the function to clone my wallpaper repo
 source ../functions/wallpaper
@@ -22,11 +32,16 @@ else
     exit
 
 fi
+# Clones my dotfiles repo
+[ -d $DOTFILES_REPO_PATH ] || git clone https://github.com/phoenix988/dotfiles.git $DOTFILES_REPO_PATH
 
-[ -d $DOTFILES_REPO_PATH ] || git clone https://github.com/phoenix988/dotfiles.git
+# Clones my dmscripts repo
+[ -d $DMSCRIPTS_REPO_PATH ] || git clone https://github.com/phoenix988/dmscripts.git $DMSCRIPTS_REPO_PATH
 
+# Clone my wallpapers
 wallpaper
 
+# Declare the array with all my dotfiles
 declare -A CONFIGS_MV
 
 CONFIGS_MV[$HOME/.config/qtile]="$DOTFILES_REPO_PATH/.config"
@@ -62,25 +77,55 @@ CONFIGS_MV[$HOME/.spectrwm.conf]="$DOTFILES_REPO_PATH"
 CONFIGS_MV[$HOME/.Xresources]="$DOTFILES_REPO_PATH"
 CONFIGS_MV[$HOME/.tmux.conf.local]="$DOTFILES_REPO_PATH"
 CONFIGS_MV[$HOME/.scripts]="$DOTFILES_REPO_PATH"
-CONFIGS_MV[$HOME/.dmenu]="$DOTFILES_REPO_PATH"
+CONFIGS_MV[$HOME/.dmenu]="$DMSCRIPTS_REPO_PATH"
+CONFIGS_MV[$HOME/.dmenu/.config]="$DMSCRIPTS_REPO_PATH"
 CONFIGS_MV[$HOME/Documents/lists]="$DOTFILES_REPO_PATH/Documents"
 CONFIGS_MV[$HOME/.local/share/applications]="$DOTFILES_REPO_PATH/.local/share"
 
 
+
+# Installs zsh if its needed
+if command_exist apt ; then
+
+command_exist zsh || printf '%s\n' "ZSH Not Installed: Installing"
+command_exist zsh || sudo apt install -y zsh &> /dev/null
+
+elif command_exist pacman ; then
+
+command_exist zsh || printf '%s\n' "ZSH Not Installed: Installing"
+command_exist zsh || sudo pacman -S --noconfirm zsh &> /dev/null
+
+elif command_exist dnf ; then
+
+command_exist zsh || printf '%s\n' "ZSH Not Installed: Installing"
+command_exist zsh || sudo dnf install -y zsh &> /dev/null
+
+fi
+
+# If it failed to install zsh script will exit here
+# Because otherwise oh my zsh will not be able to be installed 
+command_exist zsh || error
+
+# Installs oh-my-zsh framework
 bash ./ohmyzsh.sh
 
+# Installs the plugins I use
 bash ./zsh-plugins
 
 clear
 
 # Moves all my configs from my dotfile repo to my HOME directory
+# Using rsync for moving them and it will delete all the files in the 
+# destination direcotry if those files doesn't exist in the source directory
 for MV in $(printf '%s\n' "${!CONFIGS_MV[@]}") ; do
 
        CONFIG=$(printf $MV | awk -F "/" '{print $NF}')  
 
-       CONFIG_DOTFILE=$(printf '%s\n' "${CONFIGS_MV["${MV}"]}" | sed "s|$DOTFILES_REPO_PATH|$HOME|g" | awk -v conf=$CONFIG '{print $0 "/"}')
+       CONFIG_DOTFILE=$(printf '%s\n' "${CONFIGS_MV["${MV}"]}" | sed -e "s|$DOTFILES_REPO_PATH|$HOME|g" -e "s|$DMSCRIPTS_REPO_PATH|$HOME|g" | awk -v conf=$CONFIG '{print $0 "/"}')
 
        PATH_TO_COPY_FROM=$(printf '%s\n' "${CONFIGS_MV["${MV}"]}" | awk -v conf=$CONFIG '{print $0  "/" conf}' )
-       
+
+
        rsync -avh --delete $PATH_TO_COPY_FROM $CONFIG_DOTFILE
-done
+
+   done
